// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: loadbalancer/v1/loadbalancer.proto

package loadbalancerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateConfigRequest struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Hosts *[]*Host               `protobuf:"bytes,1,rep,name=hosts"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateConfigRequest) Reset() {
	*x = UpdateConfigRequest{}
	mi := &file_loadbalancer_v1_loadbalancer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigRequest) ProtoMessage() {}

func (x *UpdateConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loadbalancer_v1_loadbalancer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdateConfigRequest) GetHosts() []*Host {
	if x != nil {
		if x.xxx_hidden_Hosts != nil {
			return *x.xxx_hidden_Hosts
		}
	}
	return nil
}

func (x *UpdateConfigRequest) SetHosts(v []*Host) {
	x.xxx_hidden_Hosts = &v
}

type UpdateConfigRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Hosts []*Host
}

func (b0 UpdateConfigRequest_builder) Build() *UpdateConfigRequest {
	m0 := &UpdateConfigRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Hosts = &b.Hosts
	return m0
}

type Host struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Host        *string                `protobuf:"bytes,1,opt,name=host"`
	xxx_hidden_Targets     []string               `protobuf:"bytes,2,rep,name=targets"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Host) Reset() {
	*x = Host{}
	mi := &file_loadbalancer_v1_loadbalancer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Host) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Host) ProtoMessage() {}

func (x *Host) ProtoReflect() protoreflect.Message {
	mi := &file_loadbalancer_v1_loadbalancer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Host) GetHost() string {
	if x != nil {
		if x.xxx_hidden_Host != nil {
			return *x.xxx_hidden_Host
		}
		return ""
	}
	return ""
}

func (x *Host) GetTargets() []string {
	if x != nil {
		return x.xxx_hidden_Targets
	}
	return nil
}

func (x *Host) SetHost(v string) {
	x.xxx_hidden_Host = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *Host) SetTargets(v []string) {
	x.xxx_hidden_Targets = v
}

func (x *Host) HasHost() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Host) ClearHost() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Host = nil
}

type Host_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Host    *string
	Targets []string
}

func (b0 Host_builder) Build() *Host {
	m0 := &Host{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Host != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Host = b.Host
	}
	x.xxx_hidden_Targets = b.Targets
	return m0
}

type UpdateConfigResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Status      *string                `protobuf:"bytes,1,opt,name=status"`
	xxx_hidden_Message     *string                `protobuf:"bytes,2,opt,name=message"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UpdateConfigResponse) Reset() {
	*x = UpdateConfigResponse{}
	mi := &file_loadbalancer_v1_loadbalancer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigResponse) ProtoMessage() {}

func (x *UpdateConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loadbalancer_v1_loadbalancer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdateConfigResponse) GetStatus() string {
	if x != nil {
		if x.xxx_hidden_Status != nil {
			return *x.xxx_hidden_Status
		}
		return ""
	}
	return ""
}

func (x *UpdateConfigResponse) GetMessage() string {
	if x != nil {
		if x.xxx_hidden_Message != nil {
			return *x.xxx_hidden_Message
		}
		return ""
	}
	return ""
}

func (x *UpdateConfigResponse) SetStatus(v string) {
	x.xxx_hidden_Status = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *UpdateConfigResponse) SetMessage(v string) {
	x.xxx_hidden_Message = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *UpdateConfigResponse) HasStatus() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *UpdateConfigResponse) HasMessage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *UpdateConfigResponse) ClearStatus() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Status = nil
}

func (x *UpdateConfigResponse) ClearMessage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Message = nil
}

type UpdateConfigResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Status  *string
	Message *string
}

func (b0 UpdateConfigResponse_builder) Build() *UpdateConfigResponse {
	m0 := &UpdateConfigResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Status != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Status = b.Status
	}
	if b.Message != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Message = b.Message
	}
	return m0
}

var File_loadbalancer_v1_loadbalancer_proto protoreflect.FileDescriptor

const file_loadbalancer_v1_loadbalancer_proto_rawDesc = "" +
	"\n" +
	"\"loadbalancer/v1/loadbalancer.proto\x12\x0floadbalancer.v1\x1a!google/protobuf/go_features.proto\"B\n" +
	"\x13UpdateConfigRequest\x12+\n" +
	"\x05hosts\x18\x01 \x03(\v2\x15.loadbalancer.v1.HostR\x05hosts\"4\n" +
	"\x04Host\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x18\n" +
	"\atargets\x18\x02 \x03(\tR\atargets\"H\n" +
	"\x14UpdateConfigResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2t\n" +
	"\x13LoadbalancerService\x12]\n" +
	"\fUpdateConfig\x12$.loadbalancer.v1.UpdateConfigRequest\x1a%.loadbalancer.v1.UpdateConfigResponse\"\x00B\xc6\x01\n" +
	"\x13com.loadbalancer.v1B\x11LoadbalancerProtoP\x01Z7blackprism.org/noyra/api/loadbalancer/v1;loadbalancerv1\xa2\x02\x03LXX\xaa\x02\x0fLoadbalancer.V1\xca\x02\x0fLoadbalancer\\V1\xe2\x02\x1bLoadbalancer\\V1\\GPBMetadata\xea\x02\x10Loadbalancer::V1\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_loadbalancer_v1_loadbalancer_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_loadbalancer_v1_loadbalancer_proto_goTypes = []any{
	(*UpdateConfigRequest)(nil),  // 0: loadbalancer.v1.UpdateConfigRequest
	(*Host)(nil),                 // 1: loadbalancer.v1.Host
	(*UpdateConfigResponse)(nil), // 2: loadbalancer.v1.UpdateConfigResponse
}
var file_loadbalancer_v1_loadbalancer_proto_depIdxs = []int32{
	1, // 0: loadbalancer.v1.UpdateConfigRequest.hosts:type_name -> loadbalancer.v1.Host
	0, // 1: loadbalancer.v1.LoadbalancerService.UpdateConfig:input_type -> loadbalancer.v1.UpdateConfigRequest
	2, // 2: loadbalancer.v1.LoadbalancerService.UpdateConfig:output_type -> loadbalancer.v1.UpdateConfigResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_loadbalancer_v1_loadbalancer_proto_init() }
func file_loadbalancer_v1_loadbalancer_proto_init() {
	if File_loadbalancer_v1_loadbalancer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_loadbalancer_v1_loadbalancer_proto_rawDesc), len(file_loadbalancer_v1_loadbalancer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_loadbalancer_v1_loadbalancer_proto_goTypes,
		DependencyIndexes: file_loadbalancer_v1_loadbalancer_proto_depIdxs,
		MessageInfos:      file_loadbalancer_v1_loadbalancer_proto_msgTypes,
	}.Build()
	File_loadbalancer_v1_loadbalancer_proto = out.File
	file_loadbalancer_v1_loadbalancer_proto_goTypes = nil
	file_loadbalancer_v1_loadbalancer_proto_depIdxs = nil
}
