// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: loadbalancer/v1/loadbalancer.proto

package loadbalancerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LoadbalancerService_UpdateConfig_FullMethodName = "/loadbalancer.v1.LoadbalancerService/UpdateConfig"
)

// LoadbalancerServiceClient is the client API for LoadbalancerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LoadbalancerServiceClient interface {
	UpdateConfig(ctx context.Context, in *UpdateConfigRequest, opts ...grpc.CallOption) (*UpdateConfigResponse, error)
}

type loadbalancerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLoadbalancerServiceClient(cc grpc.ClientConnInterface) LoadbalancerServiceClient {
	return &loadbalancerServiceClient{cc}
}

func (c *loadbalancerServiceClient) UpdateConfig(ctx context.Context, in *UpdateConfigRequest, opts ...grpc.CallOption) (*UpdateConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateConfigResponse)
	err := c.cc.Invoke(ctx, LoadbalancerService_UpdateConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoadbalancerServiceServer is the server API for LoadbalancerService service.
// All implementations must embed UnimplementedLoadbalancerServiceServer
// for forward compatibility.
type LoadbalancerServiceServer interface {
	UpdateConfig(context.Context, *UpdateConfigRequest) (*UpdateConfigResponse, error)
	mustEmbedUnimplementedLoadbalancerServiceServer()
}

// UnimplementedLoadbalancerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLoadbalancerServiceServer struct{}

func (UnimplementedLoadbalancerServiceServer) UpdateConfig(context.Context, *UpdateConfigRequest) (*UpdateConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateConfig not implemented")
}
func (UnimplementedLoadbalancerServiceServer) mustEmbedUnimplementedLoadbalancerServiceServer() {}
func (UnimplementedLoadbalancerServiceServer) testEmbeddedByValue()                             {}

// UnsafeLoadbalancerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LoadbalancerServiceServer will
// result in compilation errors.
type UnsafeLoadbalancerServiceServer interface {
	mustEmbedUnimplementedLoadbalancerServiceServer()
}

func RegisterLoadbalancerServiceServer(s grpc.ServiceRegistrar, srv LoadbalancerServiceServer) {
	// If the following call pancis, it indicates UnimplementedLoadbalancerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LoadbalancerService_ServiceDesc, srv)
}

func _LoadbalancerService_UpdateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoadbalancerServiceServer).UpdateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoadbalancerService_UpdateConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoadbalancerServiceServer).UpdateConfig(ctx, req.(*UpdateConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LoadbalancerService_ServiceDesc is the grpc.ServiceDesc for LoadbalancerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LoadbalancerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "loadbalancer.v1.LoadbalancerService",
	HandlerType: (*LoadbalancerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateConfig",
			Handler:    _LoadbalancerService_UpdateConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "loadbalancer/v1/loadbalancer.proto",
}
