package component

import "time"

type ContainerInspected struct {
	Mounts []ContainerInspectedMount `json:"Mounts"`
}

type ContainerInspectedMount struct {
	Destination string   `json:"Destination"`
	Driver      string   `json:"Driver"`
	Mode        string   `json:"Mode"`
	Name        string   `json:"Name"`
	Options     []string `json:"Options"`
	Propagation string   `json:"Propagation"`
	RW          bool     `json:"RW"`
	Source      string   `json:"Source"`
	SubPath     string   `json:"SubPath"`
	Type        string   `json:"Type"`
}

type AutoGeneratedInspected struct {
	AppArmorProfile string   `json:"AppArmorProfile"`
	Args            []string `json:"Args"`
	BoundingCaps    []string `json:"BoundingCaps"`
	Config          struct {
		Annotations struct {
			Property1 string `json:"property1"`
			Property2 string `json:"property2"`
		} `json:"Annotations"`
		AttachStderr  bool     `json:"AttachStderr"`
		AttachStdin   bool     `json:"AttachStdin"`
		AttachStdout  bool     `json:"AttachStdout"`
		ChrootDirs    []string `json:"ChrootDirs"`
		Cmd           []string `json:"Cmd"`
		CreateCommand []string `json:"CreateCommand"`
		Domainname    string   `json:"Domainname"`
		Entrypoint    []string `json:"Entrypoint"`
		Env           []string `json:"Env"`
		ExposedPorts  struct {
			Property1 struct {
			} `json:"property1"`
			Property2 struct {
			} `json:"property2"`
		} `json:"ExposedPorts"`
		HealthLogDestination string `json:"HealthLogDestination"`
		Healthcheck          struct {
			Interval      int      `json:"Interval"`
			Retries       int      `json:"Retries"`
			StartInterval int      `json:"StartInterval"`
			StartPeriod   int      `json:"StartPeriod"`
			Test          []string `json:"Test"`
			Timeout       int      `json:"Timeout"`
		} `json:"Healthcheck"`
		HealthcheckMaxLogCount     int    `json:"HealthcheckMaxLogCount"`
		HealthcheckMaxLogSize      int    `json:"HealthcheckMaxLogSize"`
		HealthcheckOnFailureAction string `json:"HealthcheckOnFailureAction"`
		Hostname                   string `json:"Hostname"`
		Image                      string `json:"Image"`
		Labels                     struct {
			Property1 string `json:"property1"`
			Property2 string `json:"property2"`
		} `json:"Labels"`
		OnBuild   string `json:"OnBuild"`
		OpenStdin bool   `json:"OpenStdin"`
		Passwd    bool   `json:"Passwd"`
		Secrets   []struct {
			GID  int    `json:"GID"`
			ID   string `json:"ID"`
			Mode int    `json:"Mode"`
			Name string `json:"Name"`
			UID  int    `json:"UID"`
		} `json:"Secrets"`
		StartupHealthCheck struct {
			Interval      int      `json:"Interval"`
			Retries       int      `json:"Retries"`
			StartInterval int      `json:"StartInterval"`
			StartPeriod   int      `json:"StartPeriod"`
			Successes     int      `json:"Successes"`
			Test          []string `json:"Test"`
			Timeout       int      `json:"Timeout"`
		} `json:"StartupHealthCheck"`
		StdinOnce   bool   `json:"StdinOnce"`
		StopSignal  string `json:"StopSignal"`
		StopTimeout int    `json:"StopTimeout"`
		SystemdMode bool   `json:"SystemdMode"`
		Timeout     int    `json:"Timeout"`
		Timezone    string `json:"Timezone"`
		Tty         bool   `json:"Tty"`
		Umask       string `json:"Umask"`
		User        string `json:"User"`
		Volumes     struct {
			Property1 struct {
			} `json:"property1"`
			Property2 struct {
			} `json:"property2"`
		} `json:"Volumes"`
		WorkingDir     string `json:"WorkingDir"`
		SdNotifyMode   string `json:"sdNotifyMode"`
		SdNotifySocket string `json:"sdNotifySocket"`
	} `json:"Config"`
	ConmonPidFile string    `json:"ConmonPidFile"`
	Created       time.Time `json:"Created"`
	Dependencies  []string  `json:"Dependencies"`
	Driver        string    `json:"Driver"`
	EffectiveCaps []string  `json:"EffectiveCaps"`
	ExecIDs       []string  `json:"ExecIDs"`
	GraphDriver   struct {
		Data struct {
			Property1 string `json:"property1"`
			Property2 string `json:"property2"`
		} `json:"Data"`
		Name string `json:"Name"`
	} `json:"GraphDriver"`
	HostConfig struct {
		Annotations struct {
			Property1 string `json:"property1"`
			Property2 string `json:"property2"`
		} `json:"Annotations"`
		AutoRemove         bool     `json:"AutoRemove"`
		AutoRemoveImage    bool     `json:"AutoRemoveImage"`
		Binds              []string `json:"Binds"`
		BlkioDeviceReadBps []struct {
			Path string `json:"Path"`
			Rate int    `json:"Rate"`
		} `json:"BlkioDeviceReadBps"`
		BlkioDeviceReadIOps []struct {
			Path string `json:"Path"`
			Rate int    `json:"Rate"`
		} `json:"BlkioDeviceReadIOps"`
		BlkioDeviceWriteBps []struct {
			Path string `json:"Path"`
			Rate int    `json:"Rate"`
		} `json:"BlkioDeviceWriteBps"`
		BlkioDeviceWriteIOps []struct {
			Path string `json:"Path"`
			Rate int    `json:"Rate"`
		} `json:"BlkioDeviceWriteIOps"`
		BlkioWeight       int `json:"BlkioWeight"`
		BlkioWeightDevice []struct {
			Path   string `json:"Path"`
			Weight int    `json:"Weight"`
		} `json:"BlkioWeightDevice"`
		CapAdd     []string `json:"CapAdd"`
		CapDrop    []string `json:"CapDrop"`
		Cgroup     string   `json:"Cgroup"`
		CgroupConf struct {
			Property1 string `json:"property1"`
			Property2 string `json:"property2"`
		} `json:"CgroupConf"`
		CgroupManager      string `json:"CgroupManager"`
		CgroupMode         string `json:"CgroupMode"`
		CgroupParent       string `json:"CgroupParent"`
		Cgroups            string `json:"Cgroups"`
		ConsoleSize        []int  `json:"ConsoleSize"`
		ContainerIDFile    string `json:"ContainerIDFile"`
		CPUCount           int    `json:"CpuCount"`
		CPUPercent         int    `json:"CpuPercent"`
		CPUPeriod          int    `json:"CpuPeriod"`
		CPUQuota           int    `json:"CpuQuota"`
		CPURealtimePeriod  int    `json:"CpuRealtimePeriod"`
		CPURealtimeRuntime int    `json:"CpuRealtimeRuntime"`
		CPUShares          int    `json:"CpuShares"`
		CpusetCpus         string `json:"CpusetCpus"`
		CpusetMems         string `json:"CpusetMems"`
		Devices            []struct {
			CgroupPermissions string `json:"CgroupPermissions"`
			PathInContainer   string `json:"PathInContainer"`
			PathOnHost        string `json:"PathOnHost"`
		} `json:"Devices"`
		DiskQuota  int      `json:"DiskQuota"`
		DNS        []string `json:"Dns"`
		DNSOptions []string `json:"DnsOptions"`
		DNSSearch  []string `json:"DnsSearch"`
		ExtraHosts []string `json:"ExtraHosts"`
		GroupAdd   []string `json:"GroupAdd"`
		HostsFile  string   `json:"HostsFile"`
		IDMappings struct {
			GidMap []string `json:"GidMap"`
			UIDMap []string `json:"UidMap"`
		} `json:"IDMappings"`
		IOMaximumBandwidth int      `json:"IOMaximumBandwidth"`
		IOMaximumIOps      int      `json:"IOMaximumIOps"`
		Init               bool     `json:"Init"`
		IntelRdtClosID     string   `json:"IntelRdtClosID"`
		IpcMode            string   `json:"IpcMode"`
		Isolation          string   `json:"Isolation"`
		KernelMemory       int      `json:"KernelMemory"`
		Links              []string `json:"Links"`
		LogConfig          struct {
			Config struct {
				Property1 string `json:"property1"`
				Property2 string `json:"property2"`
			} `json:"Config"`
			Path string `json:"Path"`
			Size string `json:"Size"`
			Tag  string `json:"Tag"`
			Type string `json:"Type"`
		} `json:"LogConfig"`
		Memory            int    `json:"Memory"`
		MemoryReservation int    `json:"MemoryReservation"`
		MemorySwap        int    `json:"MemorySwap"`
		MemorySwappiness  int    `json:"MemorySwappiness"`
		NanoCpus          int    `json:"NanoCpus"`
		NetworkMode       string `json:"NetworkMode"`
		OomKillDisable    bool   `json:"OomKillDisable"`
		OomScoreAdj       int    `json:"OomScoreAdj"`
		PidMode           string `json:"PidMode"`
		PidsLimit         int    `json:"PidsLimit"`
		PortBindings      struct {
			Property1 []struct {
				HostIP   string `json:"HostIp"`
				HostPort string `json:"HostPort"`
			} `json:"property1"`
			Property2 []struct {
				HostIP   string `json:"HostIp"`
				HostPort string `json:"HostPort"`
			} `json:"property2"`
		} `json:"PortBindings"`
		Privileged      bool `json:"Privileged"`
		PublishAllPorts bool `json:"PublishAllPorts"`
		ReadonlyRootfs  bool `json:"ReadonlyRootfs"`
		RestartPolicy   struct {
			MaximumRetryCount int    `json:"MaximumRetryCount"`
			Name              string `json:"Name"`
		} `json:"RestartPolicy"`
		Runtime     string   `json:"Runtime"`
		SecurityOpt []string `json:"SecurityOpt"`
		ShmSize     int      `json:"ShmSize"`
		Tmpfs       struct {
			Property1 string `json:"property1"`
			Property2 string `json:"property2"`
		} `json:"Tmpfs"`
		UTSMode string `json:"UTSMode"`
		Ulimits []struct {
			Hard int    `json:"Hard"`
			Name string `json:"Name"`
			Soft int    `json:"Soft"`
		} `json:"Ulimits"`
		UsernsMode   string   `json:"UsernsMode"`
		VolumeDriver string   `json:"VolumeDriver"`
		VolumesFrom  []string `json:"VolumesFrom"`
	} `json:"HostConfig"`
	HostnamePath            string `json:"HostnamePath"`
	HostsPath               string `json:"HostsPath"`
	ID                      string `json:"Id"`
	Image                   string `json:"Image"`
	ImageDigest             string `json:"ImageDigest"`
	ImageName               string `json:"ImageName"`
	IsInfra                 bool   `json:"IsInfra"`
	IsService               bool   `json:"IsService"`
	KubeExitCodePropagation string `json:"KubeExitCodePropagation"`
	MountLabel              string `json:"MountLabel"`

	Name            string `json:"Name"`
	Namespace       string `json:"Namespace"`
	NetworkSettings struct {
		AdditionalMACAddresses []string `json:"AdditionalMACAddresses"`
		Bridge                 string   `json:"Bridge"`
		EndpointID             string   `json:"EndpointID"`
		Gateway                string   `json:"Gateway"`
		GlobalIPv6Address      string   `json:"GlobalIPv6Address"`
		GlobalIPv6PrefixLen    int      `json:"GlobalIPv6PrefixLen"`
		HairpinMode            bool     `json:"HairpinMode"`
		IPAddress              string   `json:"IPAddress"`
		IPPrefixLen            int      `json:"IPPrefixLen"`
		IPv6Gateway            string   `json:"IPv6Gateway"`
		LinkLocalIPv6Address   string   `json:"LinkLocalIPv6Address"`
		LinkLocalIPv6PrefixLen int      `json:"LinkLocalIPv6PrefixLen"`
		MacAddress             string   `json:"MacAddress"`
		Networks               struct {
			Property1 struct {
				AdditionalMACAddresses []string `json:"AdditionalMACAddresses"`
				Aliases                []string `json:"Aliases"`
				DriverOpts             struct {
					Property1 string `json:"property1"`
					Property2 string `json:"property2"`
				} `json:"DriverOpts"`
				EndpointID          string `json:"EndpointID"`
				Gateway             string `json:"Gateway"`
				GlobalIPv6Address   string `json:"GlobalIPv6Address"`
				GlobalIPv6PrefixLen int    `json:"GlobalIPv6PrefixLen"`
				IPAMConfig          struct {
					Property1 string `json:"property1"`
					Property2 string `json:"property2"`
				} `json:"IPAMConfig"`
				IPAddress            string   `json:"IPAddress"`
				IPPrefixLen          int      `json:"IPPrefixLen"`
				IPv6Gateway          string   `json:"IPv6Gateway"`
				Links                []string `json:"Links"`
				MacAddress           string   `json:"MacAddress"`
				NetworkID            string   `json:"NetworkID"`
				SecondaryIPAddresses []struct {
					Addr         string `json:"Addr"`
					PrefixLength int    `json:"PrefixLength"`
				} `json:"SecondaryIPAddresses"`
				SecondaryIPv6Addresses []struct {
					Addr         string `json:"Addr"`
					PrefixLength int    `json:"PrefixLength"`
				} `json:"SecondaryIPv6Addresses"`
			} `json:"property1"`
			Property2 struct {
				AdditionalMACAddresses []string `json:"AdditionalMACAddresses"`
				Aliases                []string `json:"Aliases"`
				DriverOpts             struct {
					Property1 string `json:"property1"`
					Property2 string `json:"property2"`
				} `json:"DriverOpts"`
				EndpointID          string `json:"EndpointID"`
				Gateway             string `json:"Gateway"`
				GlobalIPv6Address   string `json:"GlobalIPv6Address"`
				GlobalIPv6PrefixLen int    `json:"GlobalIPv6PrefixLen"`
				IPAMConfig          struct {
					Property1 string `json:"property1"`
					Property2 string `json:"property2"`
				} `json:"IPAMConfig"`
				IPAddress            string   `json:"IPAddress"`
				IPPrefixLen          int      `json:"IPPrefixLen"`
				IPv6Gateway          string   `json:"IPv6Gateway"`
				Links                []string `json:"Links"`
				MacAddress           string   `json:"MacAddress"`
				NetworkID            string   `json:"NetworkID"`
				SecondaryIPAddresses []struct {
					Addr         string `json:"Addr"`
					PrefixLength int    `json:"PrefixLength"`
				} `json:"SecondaryIPAddresses"`
				SecondaryIPv6Addresses []struct {
					Addr         string `json:"Addr"`
					PrefixLength int    `json:"PrefixLength"`
				} `json:"SecondaryIPv6Addresses"`
			} `json:"property2"`
		} `json:"Networks"`
		Ports struct {
			Property1 []struct {
				HostIP   string `json:"HostIp"`
				HostPort string `json:"HostPort"`
			} `json:"property1"`
			Property2 []struct {
				HostIP   string `json:"HostIp"`
				HostPort string `json:"HostPort"`
			} `json:"property2"`
		} `json:"Ports"`
		SandboxID            string `json:"SandboxID"`
		SandboxKey           string `json:"SandboxKey"`
		SecondaryIPAddresses []struct {
			Addr         string `json:"Addr"`
			PrefixLength int    `json:"PrefixLength"`
		} `json:"SecondaryIPAddresses"`
		SecondaryIPv6Addresses []struct {
			Addr         string `json:"Addr"`
			PrefixLength int    `json:"PrefixLength"`
		} `json:"SecondaryIPv6Addresses"`
	} `json:"NetworkSettings"`
	OCIConfigPath  string `json:"OCIConfigPath"`
	OCIRuntime     string `json:"OCIRuntime"`
	Path           string `json:"Path"`
	PidFile        string `json:"PidFile"`
	Pod            string `json:"Pod"`
	ProcessLabel   string `json:"ProcessLabel"`
	ResolvConfPath string `json:"ResolvConfPath"`
	RestartCount   int    `json:"RestartCount"`
	Rootfs         string `json:"Rootfs"`
	SizeRootFs     int    `json:"SizeRootFs"`
	SizeRw         int    `json:"SizeRw"`
	State          struct {
		CgroupPath     string    `json:"CgroupPath"`
		CheckpointLog  string    `json:"CheckpointLog"`
		CheckpointPath string    `json:"CheckpointPath"`
		Checkpointed   bool      `json:"Checkpointed"`
		CheckpointedAt time.Time `json:"CheckpointedAt"`
		ConmonPid      int       `json:"ConmonPid"`
		Dead           bool      `json:"Dead"`
		Error          string    `json:"Error"`
		ExitCode       int       `json:"ExitCode"`
		FinishedAt     time.Time `json:"FinishedAt"`
		Health         struct {
			FailingStreak int `json:"FailingStreak"`
			Log           []struct {
				End      string `json:"End"`
				ExitCode int    `json:"ExitCode"`
				Output   string `json:"Output"`
				Start    string `json:"Start"`
			} `json:"Log"`
			Status string `json:"Status"`
		} `json:"Health"`
		OOMKilled     bool      `json:"OOMKilled"`
		OciVersion    string    `json:"OciVersion"`
		Paused        bool      `json:"Paused"`
		Pid           int       `json:"Pid"`
		Restarting    bool      `json:"Restarting"`
		RestoreLog    string    `json:"RestoreLog"`
		Restored      bool      `json:"Restored"`
		RestoredAt    time.Time `json:"RestoredAt"`
		Running       bool      `json:"Running"`
		StartedAt     time.Time `json:"StartedAt"`
		Status        string    `json:"Status"`
		StoppedByUser bool      `json:"StoppedByUser"`
	} `json:"State"`
	StaticDir        string `json:"StaticDir"`
	UseImageHostname bool   `json:"UseImageHostname"`
	UseImageHosts    bool   `json:"UseImageHosts"`
	LockNumber       int    `json:"lockNumber"`
}
