package component

import "time"

type Container struct {
	State  string            `json:"State"`
	Labels map[string]string `json:"Labels"`
	Mounts []string          `json:"Mounts"`
}

type AutoGeneratedContainer []struct {
	AutoRemove   bool        `json:"AutoRemove"`
	CIDFile      string      `json:"CIDFile"`
	Command      []string    `json:"Command"`
	Created      time.Time   `json:"Created"`
	CreatedAt    string      `json:"CreatedAt"`
	ExitCode     int         `json:"ExitCode"`
	Exited       bool        `json:"Exited"`
	ExitedAt     int         `json:"ExitedAt"`
	ExposedPorts interface{} `json:"ExposedPorts"`
	ID           string      `json:"Id"`
	Image        string      `json:"Image"`
	ImageID      string      `json:"ImageID"`
	IsInfra      bool        `json:"IsInfra"`

	Names      []string `json:"Names"`
	Namespaces struct {
		Cgroup string `json:"Cgroup"`
		Ipc    string `json:"Ipc"`
		Mnt    string `json:"Mnt"`
		Net    string `json:"Net"`
		Pidns  string `json:"Pidns"`
		User   string `json:"User"`
		Uts    string `json:"Uts"`
	} `json:"Namespaces"`
	Networks []string `json:"Networks"`
	Pid      int      `json:"Pid"`
	Pod      string   `json:"Pod"`
	PodName  string   `json:"PodName"`
	Ports    []struct {
		ContainerPort int    `json:"container_port"`
		HostIP        string `json:"host_ip"`
		HostPort      int    `json:"host_port"`
		Protocol      string `json:"protocol"`
		Range         int    `json:"range"`
	} `json:"Ports"`
	Restarts int `json:"Restarts"`
	Size     struct {
		RootFsSize int `json:"rootFsSize"`
		RwSize     int `json:"rwSize"`
	} `json:"Size"`
	StartedAt int    `json:"StartedAt"`
	State     string `json:"State"`
	Status    string `json:"Status"`
}
