package component

import "time"

type Network struct {
	Name    string          `json:"name"`
	Driver  string          `json:"driver"`
	Subnets []NetworkSubnet `json:"subnets"`
}

type NetworkSubnet struct {
	Gateway    string `json:"gateway"`
	LeaseRange struct {
		EndIP   string `json:"end_ip"`
		StartIP string `json:"start_ip"`
	} `json:"lease_range"`
	Subnet string `json:"subnet"`
}

type AutoGenerated struct {
	Created     time.Time `json:"created"`
	DNSEnabled  bool      `json:"dns_enabled"`
	ID          string    `json:"id"`
	Internal    bool      `json:"internal"`
	IpamOptions struct {
		Property1 string `json:"property1"`
		Property2 string `json:"property2"`
	} `json:"ipam_options"`
	Ipv6Enabled bool `json:"ipv6_enabled"`
	Labels      struct {
		Property1 string `json:"property1"`
		Property2 string `json:"property2"`
	} `json:"labels"`
	NetworkDNSServers []string `json:"network_dns_servers"`
	NetworkInterface  string   `json:"network_interface"`
	Options           struct {
		Property1 string `json:"property1"`
		Property2 string `json:"property2"`
	} `json:"options"`
	Routes []struct {
		Destination string `json:"destination"`
		Gateway     string `json:"gateway"`
		Metric      int    `json:"metric"`
	} `json:"routes"`
}
