// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: agent/v1/agent.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContainerStartRequest struct {
	state                   protoimpl.MessageState   `protogen:"opaque.v1"`
	xxx_hidden_Image        *string                  `protobuf:"bytes,1,opt,name=image"`
	xxx_hidden_Name         *string                  `protobuf:"bytes,2,opt,name=name"`
	xxx_hidden_Command      []string                 `protobuf:"bytes,3,rep,name=command"`
	xxx_hidden_Labels       map[string]string        `protobuf:"bytes,4,rep,name=labels" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_Env          map[string]string        `protobuf:"bytes,5,rep,name=env" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_ExposedPorts map[uint32]string        `protobuf:"bytes,6,rep,name=exposed_ports,json=exposedPorts" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_Network      *string                  `protobuf:"bytes,7,opt,name=network"`
	xxx_hidden_Mounts       *[]*ContainerMount       `protobuf:"bytes,8,rep,name=mounts"`
	xxx_hidden_Volumes      *[]*ContainerVolume      `protobuf:"bytes,9,rep,name=volumes"`
	xxx_hidden_PortMappings *[]*ContainerPortMapping `protobuf:"bytes,10,rep,name=port_mappings,json=portMappings"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ContainerStartRequest) Reset() {
	*x = ContainerStartRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerStartRequest) ProtoMessage() {}

func (x *ContainerStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ContainerStartRequest) GetImage() string {
	if x != nil {
		if x.xxx_hidden_Image != nil {
			return *x.xxx_hidden_Image
		}
		return ""
	}
	return ""
}

func (x *ContainerStartRequest) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *ContainerStartRequest) GetCommand() []string {
	if x != nil {
		return x.xxx_hidden_Command
	}
	return nil
}

func (x *ContainerStartRequest) GetLabels() map[string]string {
	if x != nil {
		return x.xxx_hidden_Labels
	}
	return nil
}

func (x *ContainerStartRequest) GetEnv() map[string]string {
	if x != nil {
		return x.xxx_hidden_Env
	}
	return nil
}

func (x *ContainerStartRequest) GetExposedPorts() map[uint32]string {
	if x != nil {
		return x.xxx_hidden_ExposedPorts
	}
	return nil
}

func (x *ContainerStartRequest) GetNetwork() string {
	if x != nil {
		if x.xxx_hidden_Network != nil {
			return *x.xxx_hidden_Network
		}
		return ""
	}
	return ""
}

func (x *ContainerStartRequest) GetMounts() []*ContainerMount {
	if x != nil {
		if x.xxx_hidden_Mounts != nil {
			return *x.xxx_hidden_Mounts
		}
	}
	return nil
}

func (x *ContainerStartRequest) GetVolumes() []*ContainerVolume {
	if x != nil {
		if x.xxx_hidden_Volumes != nil {
			return *x.xxx_hidden_Volumes
		}
	}
	return nil
}

func (x *ContainerStartRequest) GetPortMappings() []*ContainerPortMapping {
	if x != nil {
		if x.xxx_hidden_PortMappings != nil {
			return *x.xxx_hidden_PortMappings
		}
	}
	return nil
}

func (x *ContainerStartRequest) SetImage(v string) {
	x.xxx_hidden_Image = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 10)
}

func (x *ContainerStartRequest) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 10)
}

func (x *ContainerStartRequest) SetCommand(v []string) {
	x.xxx_hidden_Command = v
}

func (x *ContainerStartRequest) SetLabels(v map[string]string) {
	x.xxx_hidden_Labels = v
}

func (x *ContainerStartRequest) SetEnv(v map[string]string) {
	x.xxx_hidden_Env = v
}

func (x *ContainerStartRequest) SetExposedPorts(v map[uint32]string) {
	x.xxx_hidden_ExposedPorts = v
}

func (x *ContainerStartRequest) SetNetwork(v string) {
	x.xxx_hidden_Network = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 10)
}

func (x *ContainerStartRequest) SetMounts(v []*ContainerMount) {
	x.xxx_hidden_Mounts = &v
}

func (x *ContainerStartRequest) SetVolumes(v []*ContainerVolume) {
	x.xxx_hidden_Volumes = &v
}

func (x *ContainerStartRequest) SetPortMappings(v []*ContainerPortMapping) {
	x.xxx_hidden_PortMappings = &v
}

func (x *ContainerStartRequest) HasImage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ContainerStartRequest) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ContainerStartRequest) HasNetwork() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *ContainerStartRequest) ClearImage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Image = nil
}

func (x *ContainerStartRequest) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Name = nil
}

func (x *ContainerStartRequest) ClearNetwork() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_Network = nil
}

type ContainerStartRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Image        *string
	Name         *string
	Command      []string
	Labels       map[string]string
	Env          map[string]string
	ExposedPorts map[uint32]string
	Network      *string
	Mounts       []*ContainerMount
	Volumes      []*ContainerVolume
	PortMappings []*ContainerPortMapping
}

func (b0 ContainerStartRequest_builder) Build() *ContainerStartRequest {
	m0 := &ContainerStartRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Image != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 10)
		x.xxx_hidden_Image = b.Image
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 10)
		x.xxx_hidden_Name = b.Name
	}
	x.xxx_hidden_Command = b.Command
	x.xxx_hidden_Labels = b.Labels
	x.xxx_hidden_Env = b.Env
	x.xxx_hidden_ExposedPorts = b.ExposedPorts
	if b.Network != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 10)
		x.xxx_hidden_Network = b.Network
	}
	x.xxx_hidden_Mounts = &b.Mounts
	x.xxx_hidden_Volumes = &b.Volumes
	x.xxx_hidden_PortMappings = &b.PortMappings
	return m0
}

type ContainerMount struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Destination *string                `protobuf:"bytes,1,opt,name=destination"`
	xxx_hidden_Type        *string                `protobuf:"bytes,2,opt,name=type"`
	xxx_hidden_Source      *string                `protobuf:"bytes,3,opt,name=source"`
	xxx_hidden_Options     []string               `protobuf:"bytes,4,rep,name=options"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ContainerMount) Reset() {
	*x = ContainerMount{}
	mi := &file_agent_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerMount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerMount) ProtoMessage() {}

func (x *ContainerMount) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ContainerMount) GetDestination() string {
	if x != nil {
		if x.xxx_hidden_Destination != nil {
			return *x.xxx_hidden_Destination
		}
		return ""
	}
	return ""
}

func (x *ContainerMount) GetType() string {
	if x != nil {
		if x.xxx_hidden_Type != nil {
			return *x.xxx_hidden_Type
		}
		return ""
	}
	return ""
}

func (x *ContainerMount) GetSource() string {
	if x != nil {
		if x.xxx_hidden_Source != nil {
			return *x.xxx_hidden_Source
		}
		return ""
	}
	return ""
}

func (x *ContainerMount) GetOptions() []string {
	if x != nil {
		return x.xxx_hidden_Options
	}
	return nil
}

func (x *ContainerMount) SetDestination(v string) {
	x.xxx_hidden_Destination = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *ContainerMount) SetType(v string) {
	x.xxx_hidden_Type = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *ContainerMount) SetSource(v string) {
	x.xxx_hidden_Source = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *ContainerMount) SetOptions(v []string) {
	x.xxx_hidden_Options = v
}

func (x *ContainerMount) HasDestination() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ContainerMount) HasType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ContainerMount) HasSource() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ContainerMount) ClearDestination() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Destination = nil
}

func (x *ContainerMount) ClearType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Type = nil
}

func (x *ContainerMount) ClearSource() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Source = nil
}

type ContainerMount_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Destination *string
	Type        *string
	Source      *string
	Options     []string
}

func (b0 ContainerMount_builder) Build() *ContainerMount {
	m0 := &ContainerMount{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Destination != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Destination = b.Destination
	}
	if b.Type != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_Type = b.Type
	}
	if b.Source != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_Source = b.Source
	}
	x.xxx_hidden_Options = b.Options
	return m0
}

type ContainerVolume struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Destination *string                `protobuf:"bytes,1,opt,name=destination"`
	xxx_hidden_Source      *string                `protobuf:"bytes,2,opt,name=source"`
	xxx_hidden_Options     []string               `protobuf:"bytes,3,rep,name=options"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ContainerVolume) Reset() {
	*x = ContainerVolume{}
	mi := &file_agent_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerVolume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerVolume) ProtoMessage() {}

func (x *ContainerVolume) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ContainerVolume) GetDestination() string {
	if x != nil {
		if x.xxx_hidden_Destination != nil {
			return *x.xxx_hidden_Destination
		}
		return ""
	}
	return ""
}

func (x *ContainerVolume) GetSource() string {
	if x != nil {
		if x.xxx_hidden_Source != nil {
			return *x.xxx_hidden_Source
		}
		return ""
	}
	return ""
}

func (x *ContainerVolume) GetOptions() []string {
	if x != nil {
		return x.xxx_hidden_Options
	}
	return nil
}

func (x *ContainerVolume) SetDestination(v string) {
	x.xxx_hidden_Destination = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *ContainerVolume) SetSource(v string) {
	x.xxx_hidden_Source = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *ContainerVolume) SetOptions(v []string) {
	x.xxx_hidden_Options = v
}

func (x *ContainerVolume) HasDestination() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ContainerVolume) HasSource() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ContainerVolume) ClearDestination() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Destination = nil
}

func (x *ContainerVolume) ClearSource() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Source = nil
}

type ContainerVolume_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Destination *string
	Source      *string
	Options     []string
}

func (b0 ContainerVolume_builder) Build() *ContainerVolume {
	m0 := &ContainerVolume{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Destination != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Destination = b.Destination
	}
	if b.Source != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Source = b.Source
	}
	x.xxx_hidden_Options = b.Options
	return m0
}

type ContainerPortMapping struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ContainerPort uint32                 `protobuf:"varint,1,opt,name=container_port,json=containerPort"`
	xxx_hidden_HostPort      uint32                 `protobuf:"varint,2,opt,name=host_port,json=hostPort"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ContainerPortMapping) Reset() {
	*x = ContainerPortMapping{}
	mi := &file_agent_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerPortMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerPortMapping) ProtoMessage() {}

func (x *ContainerPortMapping) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ContainerPortMapping) GetContainerPort() uint32 {
	if x != nil {
		return x.xxx_hidden_ContainerPort
	}
	return 0
}

func (x *ContainerPortMapping) GetHostPort() uint32 {
	if x != nil {
		return x.xxx_hidden_HostPort
	}
	return 0
}

func (x *ContainerPortMapping) SetContainerPort(v uint32) {
	x.xxx_hidden_ContainerPort = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *ContainerPortMapping) SetHostPort(v uint32) {
	x.xxx_hidden_HostPort = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *ContainerPortMapping) HasContainerPort() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ContainerPortMapping) HasHostPort() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ContainerPortMapping) ClearContainerPort() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ContainerPort = 0
}

func (x *ContainerPortMapping) ClearHostPort() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_HostPort = 0
}

type ContainerPortMapping_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ContainerPort *uint32
	HostPort      *uint32
}

func (b0 ContainerPortMapping_builder) Build() *ContainerPortMapping {
	m0 := &ContainerPortMapping{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ContainerPort != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_ContainerPort = *b.ContainerPort
	}
	if b.HostPort != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_HostPort = *b.HostPort
	}
	return m0
}

type ContainerStartResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Status      *string                `protobuf:"bytes,1,opt,name=status"`
	xxx_hidden_Message     *string                `protobuf:"bytes,2,opt,name=message"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ContainerStartResponse) Reset() {
	*x = ContainerStartResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerStartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerStartResponse) ProtoMessage() {}

func (x *ContainerStartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ContainerStartResponse) GetStatus() string {
	if x != nil {
		if x.xxx_hidden_Status != nil {
			return *x.xxx_hidden_Status
		}
		return ""
	}
	return ""
}

func (x *ContainerStartResponse) GetMessage() string {
	if x != nil {
		if x.xxx_hidden_Message != nil {
			return *x.xxx_hidden_Message
		}
		return ""
	}
	return ""
}

func (x *ContainerStartResponse) SetStatus(v string) {
	x.xxx_hidden_Status = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *ContainerStartResponse) SetMessage(v string) {
	x.xxx_hidden_Message = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *ContainerStartResponse) HasStatus() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ContainerStartResponse) HasMessage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ContainerStartResponse) ClearStatus() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Status = nil
}

func (x *ContainerStartResponse) ClearMessage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Message = nil
}

type ContainerStartResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Status  *string
	Message *string
}

func (b0 ContainerStartResponse_builder) Build() *ContainerStartResponse {
	m0 := &ContainerStartResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Status != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Status = b.Status
	}
	if b.Message != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Message = b.Message
	}
	return m0
}

type ContainerStopRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ContainerId *string                `protobuf:"bytes,1,opt,name=container_id,json=containerId"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ContainerStopRequest) Reset() {
	*x = ContainerStopRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerStopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerStopRequest) ProtoMessage() {}

func (x *ContainerStopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ContainerStopRequest) GetContainerId() string {
	if x != nil {
		if x.xxx_hidden_ContainerId != nil {
			return *x.xxx_hidden_ContainerId
		}
		return ""
	}
	return ""
}

func (x *ContainerStopRequest) SetContainerId(v string) {
	x.xxx_hidden_ContainerId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *ContainerStopRequest) HasContainerId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ContainerStopRequest) ClearContainerId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ContainerId = nil
}

type ContainerStopRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ContainerId *string
}

func (b0 ContainerStopRequest_builder) Build() *ContainerStopRequest {
	m0 := &ContainerStopRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ContainerId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_ContainerId = b.ContainerId
	}
	return m0
}

type ContainerStopResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Status      *string                `protobuf:"bytes,1,opt,name=status"`
	xxx_hidden_Message     *string                `protobuf:"bytes,2,opt,name=message"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ContainerStopResponse) Reset() {
	*x = ContainerStopResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerStopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerStopResponse) ProtoMessage() {}

func (x *ContainerStopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ContainerStopResponse) GetStatus() string {
	if x != nil {
		if x.xxx_hidden_Status != nil {
			return *x.xxx_hidden_Status
		}
		return ""
	}
	return ""
}

func (x *ContainerStopResponse) GetMessage() string {
	if x != nil {
		if x.xxx_hidden_Message != nil {
			return *x.xxx_hidden_Message
		}
		return ""
	}
	return ""
}

func (x *ContainerStopResponse) SetStatus(v string) {
	x.xxx_hidden_Status = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *ContainerStopResponse) SetMessage(v string) {
	x.xxx_hidden_Message = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *ContainerStopResponse) HasStatus() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ContainerStopResponse) HasMessage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ContainerStopResponse) ClearStatus() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Status = nil
}

func (x *ContainerStopResponse) ClearMessage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Message = nil
}

type ContainerStopResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Status  *string
	Message *string
}

func (b0 ContainerStopResponse_builder) Build() *ContainerStopResponse {
	m0 := &ContainerStopResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Status != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Status = b.Status
	}
	if b.Message != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Message = b.Message
	}
	return m0
}

type ContainerRemoveRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ContainerId *string                `protobuf:"bytes,1,opt,name=container_id,json=containerId"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ContainerRemoveRequest) Reset() {
	*x = ContainerRemoveRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerRemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerRemoveRequest) ProtoMessage() {}

func (x *ContainerRemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ContainerRemoveRequest) GetContainerId() string {
	if x != nil {
		if x.xxx_hidden_ContainerId != nil {
			return *x.xxx_hidden_ContainerId
		}
		return ""
	}
	return ""
}

func (x *ContainerRemoveRequest) SetContainerId(v string) {
	x.xxx_hidden_ContainerId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *ContainerRemoveRequest) HasContainerId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ContainerRemoveRequest) ClearContainerId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ContainerId = nil
}

type ContainerRemoveRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ContainerId *string
}

func (b0 ContainerRemoveRequest_builder) Build() *ContainerRemoveRequest {
	m0 := &ContainerRemoveRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ContainerId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_ContainerId = b.ContainerId
	}
	return m0
}

type ContainerRemoveResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Status      *string                `protobuf:"bytes,1,opt,name=status"`
	xxx_hidden_Message     *string                `protobuf:"bytes,2,opt,name=message"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ContainerRemoveResponse) Reset() {
	*x = ContainerRemoveResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerRemoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerRemoveResponse) ProtoMessage() {}

func (x *ContainerRemoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ContainerRemoveResponse) GetStatus() string {
	if x != nil {
		if x.xxx_hidden_Status != nil {
			return *x.xxx_hidden_Status
		}
		return ""
	}
	return ""
}

func (x *ContainerRemoveResponse) GetMessage() string {
	if x != nil {
		if x.xxx_hidden_Message != nil {
			return *x.xxx_hidden_Message
		}
		return ""
	}
	return ""
}

func (x *ContainerRemoveResponse) SetStatus(v string) {
	x.xxx_hidden_Status = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *ContainerRemoveResponse) SetMessage(v string) {
	x.xxx_hidden_Message = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *ContainerRemoveResponse) HasStatus() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ContainerRemoveResponse) HasMessage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ContainerRemoveResponse) ClearStatus() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Status = nil
}

func (x *ContainerRemoveResponse) ClearMessage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Message = nil
}

type ContainerRemoveResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Status  *string
	Message *string
}

func (b0 ContainerRemoveResponse_builder) Build() *ContainerRemoveResponse {
	m0 := &ContainerRemoveResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Status != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Status = b.Status
	}
	if b.Message != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Message = b.Message
	}
	return m0
}

type ContainerInfoRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ContainerId *string                `protobuf:"bytes,1,opt,name=container_id,json=containerId"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ContainerInfoRequest) Reset() {
	*x = ContainerInfoRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerInfoRequest) ProtoMessage() {}

func (x *ContainerInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ContainerInfoRequest) GetContainerId() string {
	if x != nil {
		if x.xxx_hidden_ContainerId != nil {
			return *x.xxx_hidden_ContainerId
		}
		return ""
	}
	return ""
}

func (x *ContainerInfoRequest) SetContainerId(v string) {
	x.xxx_hidden_ContainerId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *ContainerInfoRequest) HasContainerId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ContainerInfoRequest) ClearContainerId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ContainerId = nil
}

type ContainerInfoRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ContainerId *string
}

func (b0 ContainerInfoRequest_builder) Build() *ContainerInfoRequest {
	m0 := &ContainerInfoRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ContainerId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_ContainerId = b.ContainerId
	}
	return m0
}

type ContainerListRequest struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ContainersId []string               `protobuf:"bytes,1,rep,name=containers_id,json=containersId"`
	xxx_hidden_Labels       map[string]string      `protobuf:"bytes,2,rep,name=labels" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ContainerListRequest) Reset() {
	*x = ContainerListRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerListRequest) ProtoMessage() {}

func (x *ContainerListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ContainerListRequest) GetContainersId() []string {
	if x != nil {
		return x.xxx_hidden_ContainersId
	}
	return nil
}

func (x *ContainerListRequest) GetLabels() map[string]string {
	if x != nil {
		return x.xxx_hidden_Labels
	}
	return nil
}

func (x *ContainerListRequest) SetContainersId(v []string) {
	x.xxx_hidden_ContainersId = v
}

func (x *ContainerListRequest) SetLabels(v map[string]string) {
	x.xxx_hidden_Labels = v
}

type ContainerListRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ContainersId []string
	Labels       map[string]string
}

func (b0 ContainerListRequest_builder) Build() *ContainerListRequest {
	m0 := &ContainerListRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ContainersId = b.ContainersId
	x.xxx_hidden_Labels = b.Labels
	return m0
}

type ContainerListResponse struct {
	state                 protoimpl.MessageState    `protogen:"opaque.v1"`
	xxx_hidden_Containers map[string]*ContainerInfo `protobuf:"bytes,1,rep,name=containers" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ContainerListResponse) Reset() {
	*x = ContainerListResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerListResponse) ProtoMessage() {}

func (x *ContainerListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ContainerListResponse) GetContainers() map[string]*ContainerInfo {
	if x != nil {
		return x.xxx_hidden_Containers
	}
	return nil
}

func (x *ContainerListResponse) SetContainers(v map[string]*ContainerInfo) {
	x.xxx_hidden_Containers = v
}

type ContainerListResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Containers map[string]*ContainerInfo
}

func (b0 ContainerListResponse_builder) Build() *ContainerListResponse {
	m0 := &ContainerListResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Containers = b.Containers
	return m0
}

type ContainerInfo struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Name        *string                `protobuf:"bytes,2,opt,name=name"`
	xxx_hidden_Labels      map[string]string      `protobuf:"bytes,3,rep,name=labels" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_IpAddress   *string                `protobuf:"bytes,4,opt,name=ip_address,json=ipAddress"`
	xxx_hidden_ExposedPort int32                  `protobuf:"varint,5,opt,name=exposed_port,json=exposedPort"`
	xxx_hidden_State       *string                `protobuf:"bytes,6,opt,name=state"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ContainerInfo) Reset() {
	*x = ContainerInfo{}
	mi := &file_agent_v1_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerInfo) ProtoMessage() {}

func (x *ContainerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ContainerInfo) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *ContainerInfo) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *ContainerInfo) GetLabels() map[string]string {
	if x != nil {
		return x.xxx_hidden_Labels
	}
	return nil
}

func (x *ContainerInfo) GetIpAddress() string {
	if x != nil {
		if x.xxx_hidden_IpAddress != nil {
			return *x.xxx_hidden_IpAddress
		}
		return ""
	}
	return ""
}

func (x *ContainerInfo) GetExposedPort() int32 {
	if x != nil {
		return x.xxx_hidden_ExposedPort
	}
	return 0
}

func (x *ContainerInfo) GetState() string {
	if x != nil {
		if x.xxx_hidden_State != nil {
			return *x.xxx_hidden_State
		}
		return ""
	}
	return ""
}

func (x *ContainerInfo) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 6)
}

func (x *ContainerInfo) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 6)
}

func (x *ContainerInfo) SetLabels(v map[string]string) {
	x.xxx_hidden_Labels = v
}

func (x *ContainerInfo) SetIpAddress(v string) {
	x.xxx_hidden_IpAddress = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 6)
}

func (x *ContainerInfo) SetExposedPort(v int32) {
	x.xxx_hidden_ExposedPort = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 6)
}

func (x *ContainerInfo) SetState(v string) {
	x.xxx_hidden_State = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 6)
}

func (x *ContainerInfo) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ContainerInfo) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ContainerInfo) HasIpAddress() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *ContainerInfo) HasExposedPort() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *ContainerInfo) HasState() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *ContainerInfo) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *ContainerInfo) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Name = nil
}

func (x *ContainerInfo) ClearIpAddress() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_IpAddress = nil
}

func (x *ContainerInfo) ClearExposedPort() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_ExposedPort = 0
}

func (x *ContainerInfo) ClearState() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_State = nil
}

type ContainerInfo_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id          *string
	Name        *string
	Labels      map[string]string
	IpAddress   *string
	ExposedPort *int32
	State       *string
}

func (b0 ContainerInfo_builder) Build() *ContainerInfo {
	m0 := &ContainerInfo{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 6)
		x.xxx_hidden_Id = b.Id
	}
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 6)
		x.xxx_hidden_Name = b.Name
	}
	x.xxx_hidden_Labels = b.Labels
	if b.IpAddress != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 6)
		x.xxx_hidden_IpAddress = b.IpAddress
	}
	if b.ExposedPort != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 6)
		x.xxx_hidden_ExposedPort = *b.ExposedPort
	}
	if b.State != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 6)
		x.xxx_hidden_State = b.State
	}
	return m0
}

type ContainerListenerRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerListenerRequest) Reset() {
	*x = ContainerListenerRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerListenerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerListenerRequest) ProtoMessage() {}

func (x *ContainerListenerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ContainerListenerRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ContainerListenerRequest_builder) Build() *ContainerListenerRequest {
	m0 := &ContainerListenerRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ContainerListenerResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Action      *string                `protobuf:"bytes,2,opt,name=action"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ContainerListenerResponse) Reset() {
	*x = ContainerListenerResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerListenerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerListenerResponse) ProtoMessage() {}

func (x *ContainerListenerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ContainerListenerResponse) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *ContainerListenerResponse) GetAction() string {
	if x != nil {
		if x.xxx_hidden_Action != nil {
			return *x.xxx_hidden_Action
		}
		return ""
	}
	return ""
}

func (x *ContainerListenerResponse) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *ContainerListenerResponse) SetAction(v string) {
	x.xxx_hidden_Action = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *ContainerListenerResponse) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ContainerListenerResponse) HasAction() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ContainerListenerResponse) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *ContainerListenerResponse) ClearAction() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Action = nil
}

type ContainerListenerResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id     *string
	Action *string
}

func (b0 ContainerListenerResponse_builder) Build() *ContainerListenerResponse {
	m0 := &ContainerListenerResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Id = b.Id
	}
	if b.Action != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Action = b.Action
	}
	return m0
}

var File_agent_v1_agent_proto protoreflect.FileDescriptor

const file_agent_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x14agent/v1/agent.proto\x12\bagent.v1\x1a!google/protobuf/go_features.proto\"\xae\x05\n" +
	"\x15ContainerStartRequest\x12\x14\n" +
	"\x05image\x18\x01 \x01(\tR\x05image\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\acommand\x18\x03 \x03(\tR\acommand\x12C\n" +
	"\x06labels\x18\x04 \x03(\v2+.agent.v1.ContainerStartRequest.LabelsEntryR\x06labels\x12:\n" +
	"\x03env\x18\x05 \x03(\v2(.agent.v1.ContainerStartRequest.EnvEntryR\x03env\x12V\n" +
	"\rexposed_ports\x18\x06 \x03(\v21.agent.v1.ContainerStartRequest.ExposedPortsEntryR\fexposedPorts\x12\x18\n" +
	"\anetwork\x18\a \x01(\tR\anetwork\x120\n" +
	"\x06mounts\x18\b \x03(\v2\x18.agent.v1.ContainerMountR\x06mounts\x123\n" +
	"\avolumes\x18\t \x03(\v2\x19.agent.v1.ContainerVolumeR\avolumes\x12C\n" +
	"\rport_mappings\x18\n" +
	" \x03(\v2\x1e.agent.v1.ContainerPortMappingR\fportMappings\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a?\n" +
	"\x11ExposedPortsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"x\n" +
	"\x0eContainerMount\x12 \n" +
	"\vdestination\x18\x01 \x01(\tR\vdestination\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x18\n" +
	"\aoptions\x18\x04 \x03(\tR\aoptions\"e\n" +
	"\x0fContainerVolume\x12 \n" +
	"\vdestination\x18\x01 \x01(\tR\vdestination\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x18\n" +
	"\aoptions\x18\x03 \x03(\tR\aoptions\"Z\n" +
	"\x14ContainerPortMapping\x12%\n" +
	"\x0econtainer_port\x18\x01 \x01(\rR\rcontainerPort\x12\x1b\n" +
	"\thost_port\x18\x02 \x01(\rR\bhostPort\"J\n" +
	"\x16ContainerStartResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"9\n" +
	"\x14ContainerStopRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\"I\n" +
	"\x15ContainerStopResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\";\n" +
	"\x16ContainerRemoveRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\"K\n" +
	"\x17ContainerRemoveResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"9\n" +
	"\x14ContainerInfoRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\"\xba\x01\n" +
	"\x14ContainerListRequest\x12#\n" +
	"\rcontainers_id\x18\x01 \x03(\tR\fcontainersId\x12B\n" +
	"\x06labels\x18\x02 \x03(\v2*.agent.v1.ContainerListRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc0\x01\n" +
	"\x15ContainerListResponse\x12O\n" +
	"\n" +
	"containers\x18\x01 \x03(\v2/.agent.v1.ContainerListResponse.ContainersEntryR\n" +
	"containers\x1aV\n" +
	"\x0fContainersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.agent.v1.ContainerInfoR\x05value:\x028\x01\"\x83\x02\n" +
	"\rContainerInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12;\n" +
	"\x06labels\x18\x03 \x03(\v2#.agent.v1.ContainerInfo.LabelsEntryR\x06labels\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x04 \x01(\tR\tipAddress\x12!\n" +
	"\fexposed_port\x18\x05 \x01(\x05R\vexposedPort\x12\x14\n" +
	"\x05state\x18\x06 \x01(\tR\x05state\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x1a\n" +
	"\x18ContainerListenerRequest\"C\n" +
	"\x19ContainerListenerResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action2\xc9\x03\n" +
	"\fAgentService\x12U\n" +
	"\x0eContainerStart\x12\x1f.agent.v1.ContainerStartRequest\x1a .agent.v1.ContainerStartResponse\"\x00\x12R\n" +
	"\rContainerStop\x12\x1e.agent.v1.ContainerStopRequest\x1a\x1f.agent.v1.ContainerStopResponse\"\x00\x12X\n" +
	"\x0fContainerRemove\x12 .agent.v1.ContainerRemoveRequest\x1a!.agent.v1.ContainerRemoveResponse\"\x00\x12R\n" +
	"\rContainerList\x12\x1e.agent.v1.ContainerListRequest\x1a\x1f.agent.v1.ContainerListResponse\"\x00\x12`\n" +
	"\x11ContainerListener\x12\".agent.v1.ContainerListenerRequest\x1a#.agent.v1.ContainerListenerResponse\"\x000\x01B\x8e\x01\n" +
	"\fcom.agent.v1B\n" +
	"AgentProtoP\x01Z)blackprism.org/noyra/api/agent/v1;agentv1\xa2\x02\x03AXX\xaa\x02\bAgent.V1\xca\x02\bAgent\\V1\xe2\x02\x14Agent\\V1\\GPBMetadata\xea\x02\tAgent::V1\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_agent_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_agent_v1_agent_proto_goTypes = []any{
	(*ContainerStartRequest)(nil),     // 0: agent.v1.ContainerStartRequest
	(*ContainerMount)(nil),            // 1: agent.v1.ContainerMount
	(*ContainerVolume)(nil),           // 2: agent.v1.ContainerVolume
	(*ContainerPortMapping)(nil),      // 3: agent.v1.ContainerPortMapping
	(*ContainerStartResponse)(nil),    // 4: agent.v1.ContainerStartResponse
	(*ContainerStopRequest)(nil),      // 5: agent.v1.ContainerStopRequest
	(*ContainerStopResponse)(nil),     // 6: agent.v1.ContainerStopResponse
	(*ContainerRemoveRequest)(nil),    // 7: agent.v1.ContainerRemoveRequest
	(*ContainerRemoveResponse)(nil),   // 8: agent.v1.ContainerRemoveResponse
	(*ContainerInfoRequest)(nil),      // 9: agent.v1.ContainerInfoRequest
	(*ContainerListRequest)(nil),      // 10: agent.v1.ContainerListRequest
	(*ContainerListResponse)(nil),     // 11: agent.v1.ContainerListResponse
	(*ContainerInfo)(nil),             // 12: agent.v1.ContainerInfo
	(*ContainerListenerRequest)(nil),  // 13: agent.v1.ContainerListenerRequest
	(*ContainerListenerResponse)(nil), // 14: agent.v1.ContainerListenerResponse
	nil,                               // 15: agent.v1.ContainerStartRequest.LabelsEntry
	nil,                               // 16: agent.v1.ContainerStartRequest.EnvEntry
	nil,                               // 17: agent.v1.ContainerStartRequest.ExposedPortsEntry
	nil,                               // 18: agent.v1.ContainerListRequest.LabelsEntry
	nil,                               // 19: agent.v1.ContainerListResponse.ContainersEntry
	nil,                               // 20: agent.v1.ContainerInfo.LabelsEntry
}
var file_agent_v1_agent_proto_depIdxs = []int32{
	15, // 0: agent.v1.ContainerStartRequest.labels:type_name -> agent.v1.ContainerStartRequest.LabelsEntry
	16, // 1: agent.v1.ContainerStartRequest.env:type_name -> agent.v1.ContainerStartRequest.EnvEntry
	17, // 2: agent.v1.ContainerStartRequest.exposed_ports:type_name -> agent.v1.ContainerStartRequest.ExposedPortsEntry
	1,  // 3: agent.v1.ContainerStartRequest.mounts:type_name -> agent.v1.ContainerMount
	2,  // 4: agent.v1.ContainerStartRequest.volumes:type_name -> agent.v1.ContainerVolume
	3,  // 5: agent.v1.ContainerStartRequest.port_mappings:type_name -> agent.v1.ContainerPortMapping
	18, // 6: agent.v1.ContainerListRequest.labels:type_name -> agent.v1.ContainerListRequest.LabelsEntry
	19, // 7: agent.v1.ContainerListResponse.containers:type_name -> agent.v1.ContainerListResponse.ContainersEntry
	20, // 8: agent.v1.ContainerInfo.labels:type_name -> agent.v1.ContainerInfo.LabelsEntry
	12, // 9: agent.v1.ContainerListResponse.ContainersEntry.value:type_name -> agent.v1.ContainerInfo
	0,  // 10: agent.v1.AgentService.ContainerStart:input_type -> agent.v1.ContainerStartRequest
	5,  // 11: agent.v1.AgentService.ContainerStop:input_type -> agent.v1.ContainerStopRequest
	7,  // 12: agent.v1.AgentService.ContainerRemove:input_type -> agent.v1.ContainerRemoveRequest
	10, // 13: agent.v1.AgentService.ContainerList:input_type -> agent.v1.ContainerListRequest
	13, // 14: agent.v1.AgentService.ContainerListener:input_type -> agent.v1.ContainerListenerRequest
	4,  // 15: agent.v1.AgentService.ContainerStart:output_type -> agent.v1.ContainerStartResponse
	6,  // 16: agent.v1.AgentService.ContainerStop:output_type -> agent.v1.ContainerStopResponse
	8,  // 17: agent.v1.AgentService.ContainerRemove:output_type -> agent.v1.ContainerRemoveResponse
	11, // 18: agent.v1.AgentService.ContainerList:output_type -> agent.v1.ContainerListResponse
	14, // 19: agent.v1.AgentService.ContainerListener:output_type -> agent.v1.ContainerListenerResponse
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_agent_v1_agent_proto_init() }
func file_agent_v1_agent_proto_init() {
	if File_agent_v1_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_v1_agent_proto_rawDesc), len(file_agent_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_v1_agent_proto_goTypes,
		DependencyIndexes: file_agent_v1_agent_proto_depIdxs,
		MessageInfos:      file_agent_v1_agent_proto_msgTypes,
	}.Build()
	File_agent_v1_agent_proto = out.File
	file_agent_v1_agent_proto_goTypes = nil
	file_agent_v1_agent_proto_depIdxs = nil
}
