// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: certificate/v1/signer.proto

package certificatev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CertifyRequest struct {
	state                                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_CertificateSigningRequest []byte                 `protobuf:"bytes,1,opt,name=certificate_signing_request,json=certificateSigningRequest,proto3"`
	unknownFields                        protoimpl.UnknownFields
	sizeCache                            protoimpl.SizeCache
}

func (x *CertifyRequest) Reset() {
	*x = CertifyRequest{}
	mi := &file_certificate_v1_signer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertifyRequest) ProtoMessage() {}

func (x *CertifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_certificate_v1_signer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CertifyRequest) GetCertificateSigningRequest() []byte {
	if x != nil {
		return x.xxx_hidden_CertificateSigningRequest
	}
	return nil
}

func (x *CertifyRequest) SetCertificateSigningRequest(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_CertificateSigningRequest = v
}

type CertifyRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// CSR en PEM (PKCS#10)
	CertificateSigningRequest []byte
}

func (b0 CertifyRequest_builder) Build() *CertifyRequest {
	m0 := &CertifyRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_CertificateSigningRequest = b.CertificateSigningRequest
	return m0
}

type CertifyResponse struct {
	state                               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_LeafCertificate          []byte                 `protobuf:"bytes,1,opt,name=leaf_certificate,json=leafCertificate,proto3"`
	xxx_hidden_IntermediateCertificates [][]byte               `protobuf:"bytes,2,rep,name=intermediate_certificates,json=intermediateCertificates,proto3"`
	xxx_hidden_NotAfter                 *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=not_after,json=notAfter,proto3"`
	unknownFields                       protoimpl.UnknownFields
	sizeCache                           protoimpl.SizeCache
}

func (x *CertifyResponse) Reset() {
	*x = CertifyResponse{}
	mi := &file_certificate_v1_signer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertifyResponse) ProtoMessage() {}

func (x *CertifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_certificate_v1_signer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CertifyResponse) GetLeafCertificate() []byte {
	if x != nil {
		return x.xxx_hidden_LeafCertificate
	}
	return nil
}

func (x *CertifyResponse) GetIntermediateCertificates() [][]byte {
	if x != nil {
		return x.xxx_hidden_IntermediateCertificates
	}
	return nil
}

func (x *CertifyResponse) GetNotAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_NotAfter
	}
	return nil
}

func (x *CertifyResponse) SetLeafCertificate(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_LeafCertificate = v
}

func (x *CertifyResponse) SetIntermediateCertificates(v [][]byte) {
	x.xxx_hidden_IntermediateCertificates = v
}

func (x *CertifyResponse) SetNotAfter(v *timestamppb.Timestamp) {
	x.xxx_hidden_NotAfter = v
}

func (x *CertifyResponse) HasNotAfter() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_NotAfter != nil
}

func (x *CertifyResponse) ClearNotAfter() {
	x.xxx_hidden_NotAfter = nil
}

type CertifyResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Certificat feuille signé, en PEM
	LeafCertificate []byte
	// Chaîne d'intermédiaires, chacun en PEM
	// Ordre : intermédiaire direct → ... → sous-CA
	IntermediateCertificates [][]byte
	NotAfter                 *timestamppb.Timestamp
}

func (b0 CertifyResponse_builder) Build() *CertifyResponse {
	m0 := &CertifyResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_LeafCertificate = b.LeafCertificate
	x.xxx_hidden_IntermediateCertificates = b.IntermediateCertificates
	x.xxx_hidden_NotAfter = b.NotAfter
	return m0
}

var File_certificate_v1_signer_proto protoreflect.FileDescriptor

const file_certificate_v1_signer_proto_rawDesc = "" +
	"\n" +
	"\x1bcertificate/v1/signer.proto\x12\x0ecertificate.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"P\n" +
	"\x0eCertifyRequest\x12>\n" +
	"\x1bcertificate_signing_request\x18\x01 \x01(\fR\x19certificateSigningRequest\"\xb2\x01\n" +
	"\x0fCertifyResponse\x12)\n" +
	"\x10leaf_certificate\x18\x01 \x01(\fR\x0fleafCertificate\x12;\n" +
	"\x19intermediate_certificates\x18\x02 \x03(\fR\x18intermediateCertificates\x127\n" +
	"\tnot_after\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bnotAfter2[\n" +
	"\rSignerService\x12J\n" +
	"\aCertify\x12\x1e.certificate.v1.CertifyRequest\x1a\x1f.certificate.v1.CertifyResponseB\xb1\x01\n" +
	"\x12com.certificate.v1B\vSignerProtoP\x01Z5blackprism.org/noyra/api/certificate/v1;certificatev1\xa2\x02\x03CXX\xaa\x02\x0eCertificate.V1\xca\x02\x0eCertificate\\V1\xe2\x02\x1aCertificate\\V1\\GPBMetadata\xea\x02\x0fCertificate::V1b\x06proto3"

var file_certificate_v1_signer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_certificate_v1_signer_proto_goTypes = []any{
	(*CertifyRequest)(nil),        // 0: certificate.v1.CertifyRequest
	(*CertifyResponse)(nil),       // 1: certificate.v1.CertifyResponse
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_certificate_v1_signer_proto_depIdxs = []int32{
	2, // 0: certificate.v1.CertifyResponse.not_after:type_name -> google.protobuf.Timestamp
	0, // 1: certificate.v1.SignerService.Certify:input_type -> certificate.v1.CertifyRequest
	1, // 2: certificate.v1.SignerService.Certify:output_type -> certificate.v1.CertifyResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_certificate_v1_signer_proto_init() }
func file_certificate_v1_signer_proto_init() {
	if File_certificate_v1_signer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_certificate_v1_signer_proto_rawDesc), len(file_certificate_v1_signer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_certificate_v1_signer_proto_goTypes,
		DependencyIndexes: file_certificate_v1_signer_proto_depIdxs,
		MessageInfos:      file_certificate_v1_signer_proto_msgTypes,
	}.Build()
	File_certificate_v1_signer_proto = out.File
	file_certificate_v1_signer_proto_goTypes = nil
	file_certificate_v1_signer_proto_depIdxs = nil
}
